In [15]:
import pandas as pd
import numpy as np
import re
import string

import nltk
import spacy

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [3]:
from src.ingestion.load_data import DataLoader

loader = DataLoader()

df = loader.load_data(1000)

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           1000 non-null   float64
 1   title        1000 non-null   str
 2   abstract     1000 non-null   str
 3   authors      1000 non-null   str
 4   categories   1000 non-null   str
 5   update_date  1000 non-null   str
 6   category     1000 non-null   object
 7   text         1000 non-null   str
dtypes: float64(1), object(1), str(6)
memory usage: 1.8+ MB

In [4]:
df.columns

Index(['id', 'submitter', 'authors', 'title', 'comments', 'journal-ref', 'doi',
       'report-no', 'categories', 'license', 'abstract', 'versions',
       'update_date', 'authors_parsed'],
      dtype='str')

In [5]:
df = df[
    [
        "id",
        "title",
        "abstract",
        "authors",
        "categories",
        "update_date"
    ]
]

In [6]:
df.columns

Index(['id', 'title', 'abstract', 'authors', 'categories', 'update_date'], dtype='str')

In [7]:
df["category"] = df["categories"].str.split().str[0]

In [10]:
df["categories"].nunique()

309

In [11]:
df["categories"].nunique()

309

In [12]:
df["text"] = df["title"] + " " + df["abstract"]

In [18]:
df["title"][0]

'Calculation of prompt diphoton production cross sections at Tevatron and\n  LHC energies'

In [19]:
df['abstract'][0]

'  A fully differential calculation in perturbative quantum chromodynamics is\npresented for the production of massive photon pairs at hadron colliders. All\nnext-to-leading order perturbative contributions from quark-antiquark,\ngluon-(anti)quark, and gluon-gluon subprocesses are included, as well as\nall-orders resummation of initial-state gluon radiation valid at\nnext-to-next-to-leading logarithmic accuracy. The region of phase space is\nspecified in which the calculation is most reliable. Good agreement is\ndemonstrated with data from the Fermilab Tevatron, and predictions are made for\nmore detailed tests with CDF and DO data. Predictions are shown for\ndistributions of diphoton pairs produced at the energy of the Large Hadron\nCollider (LHC). Distributions of the diphoton pairs from the decay of a Higgs\nboson are contrasted with those produced from QCD processes at the LHC, showing\nthat enhanced sensitivity to the signal can be obtained with judicious\nselection of events.\n'

In [13]:
df["text"][0]

'Calculation of prompt diphoton production cross sections at Tevatron and\n  LHC energies   A fully differential calculation in perturbative quantum chromodynamics is\npresented for the production of massive photon pairs at hadron colliders. All\nnext-to-leading order perturbative contributions from quark-antiquark,\ngluon-(anti)quark, and gluon-gluon subprocesses are included, as well as\nall-orders resummation of initial-state gluon radiation valid at\nnext-to-next-to-leading logarithmic accuracy. The region of phase space is\nspecified in which the calculation is most reliable. Good agreement is\ndemonstrated with data from the Fermilab Tevatron, and predictions are made for\nmore detailed tests with CDF and DO data. Predictions are shown for\ndistributions of diphoton pairs produced at the energy of the Large Hadron\nCollider (LHC). Distributions of the diphoton pairs from the decay of a Higgs\nboson are contrasted with those produced from QCD processes at the LHC, showing\nthat enhanced sensitivity to the signal can be obtained with judicious\nselection of events.\n'

In [22]:
df.isna().sum()

id             0
title          0
abstract       0
authors        0
categories     0
update_date    0
category       0
text           0
dtype: int64

In [16]:
nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...

True

In [20]:
nlp = spacy.load("en_core_web_sm")

In [23]:
df.columns

Index(['id', 'title', 'abstract', 'authors', 'categories', 'update_date',
       'category', 'text'],
      dtype='str')

In [25]:
df.rename(columns={'text':'text_raw'}, inplace=True)

In [26]:
df["text_clean"] = df["title"] + " " + df["abstract"]

In [27]:
df.columns

Index(['id', 'title', 'abstract', 'authors', 'categories', 'update_date',
       'category', 'text_raw', 'text_clean'],
      dtype='str')

In [28]:
df.head()

,id,title,abstract,authors,categories,update_date,category,text_raw,text_clean
0,704.0001,Calculation of prompt diphoton production cros...,A fully differential calculation in perturba...,"C. Bal\'azs, E. L. Berger, P. M. Nadolsky, C.-...",hep-ph,2008-11-26,hep-ph,Calculation of prompt diphoton production cros...,Calculation of prompt diphoton production cros...
1,704.0002,Sparsity-certifying Graph Decompositions,"We describe a new algorithm, the $(k,\ell)$-...",Ileana Streinu and Louis Theran,math.CO cs.CG,2008-12-13,math.CO,Sparsity-certifying Graph Decompositions We ...,Sparsity-certifying Graph Decompositions We ...
2,704.0003,The evolution of the Earth-Moon system based o...,The evolution of Earth-Moon system is descri...,Hongjun Pan,physics.gen-ph,2008-01-13,physics.gen-ph,The evolution of the Earth-Moon system based o...,The evolution of the Earth-Moon system based o...
3,704.0004,A determinant of Stirling cycle numbers counts...,We show that a determinant of Stirling cycle...,David Callan,math.CO,2007-05-23,math.CO,A determinant of Stirling cycle numbers counts...,A determinant of Stirling cycle numbers counts...
4,704.0005,From dyadic $\Lambda_{\alpha}$ to $\Lambda_{\a...,In this paper we show how to compute the $\L...,Wael Abu-Shammala and Alberto Torchinsky,math.CA math.FA,2013-10-15,math.CA,From dyadic $\Lambda_{\alpha}$ to $\Lambda_{\a...,From dyadic $\Lambda_{\alpha}$ to $\Lambda_{\a...

# Tokenization Experiments

In [29]:
sample = df.loc[0, "text_clean"]

print(sample)

Calculation of prompt diphoton production cross sections at Tevatron and
  LHC energies   A fully differential calculation in perturbative quantum chromodynamics is
presented for the production of massive photon pairs at hadron colliders. All
next-to-leading order perturbative contributions from quark-antiquark,
gluon-(anti)quark, and gluon-gluon subprocesses are included, as well as
all-orders resummation of initial-state gluon radiation valid at
next-to-next-to-leading logarithmic accuracy. The region of phase space is
specified in which the calculation is most reliable. Good agreement is
demonstrated with data from the Fermilab Tevatron, and predictions are made for
more detailed tests with CDF and DO data. Predictions are shown for
distributions of diphoton pairs produced at the energy of the Large Hadron
Collider (LHC). Distributions of the diphoton pairs from the decay of a Higgs
boson are contrasted with those produced from QCD processes at the LHC, showing
that enhanced sensitivity to the signal can be obtained with judicious
selection of events.

In [35]:
from nltk.tokenize import word_tokenize

nltk_tokens = word_tokenize(sample)

print(nltk_tokens)
len(nltk_tokens)

['Calculation', 'of', 'prompt', 'diphoton', 'production', 'cross', 'sections', 'at', 'Tevatron', 'and', 'LHC', 'energies', 'A', 'fully', 'differential', 'calculation', 'in', 'perturbative', 'quantum', 'chromodynamics', 'is', 'presented', 'for', 'the', 'production', 'of', 'massive', 'photon', 'pairs', 'at', 'hadron', 'colliders', '.', 'All', 'next-to-leading', 'order', 'perturbative', 'contributions', 'from', 'quark-antiquark', ',', 'gluon-', '(', 'anti', ')', 'quark', ',', 'and', 'gluon-gluon', 'subprocesses', 'are', 'included', ',', 'as', 'well', 'as', 'all-orders', 'resummation', 'of', 'initial-state', 'gluon', 'radiation', 'valid', 'at', 'next-to-next-to-leading', 'logarithmic', 'accuracy', '.', 'The', 'region', 'of', 'phase', 'space', 'is', 'specified', 'in', 'which', 'the', 'calculation', 'is', 'most', 'reliable', '.', 'Good', 'agreement', 'is', 'demonstrated', 'with', 'data', 'from', 'the', 'Fermilab', 'Tevatron', ',', 'and', 'predictions', 'are', 'made', 'for', 'more', 'detailed', 'tests', 'with', 'CDF', 'and', 'DO', 'data', '.', 'Predictions', 'are', 'shown', 'for', 'distributions', 'of', 'diphoton', 'pairs', 'produced', 'at', 'the', 'energy', 'of', 'the', 'Large', 'Hadron', 'Collider', '(', 'LHC', ')', '.', 'Distributions', 'of', 'the', 'diphoton', 'pairs', 'from', 'the', 'decay', 'of', 'a', 'Higgs', 'boson', 'are', 'contrasted', 'with', 'those', 'produced', 'from', 'QCD', 'processes', 'at', 'the', 'LHC', ',', 'showing', 'that', 'enhanced', 'sensitivity', 'to', 'the', 'signal', 'can', 'be', 'obtained', 'with', 'judicious', 'selection', 'of', 'events', '.']

169

In [36]:
doc = nlp(sample)

spacy_tokens = [token.text for token in doc]

print(spacy_tokens[:50])
len(spacy_tokens)

['Calculation', 'of', 'prompt', 'diphoton', 'production', 'cross', 'sections', 'at', 'Tevatron', 'and', '\n  ', 'LHC', 'energies', '  ', 'A', 'fully', 'differential', 'calculation', 'in', 'perturbative', 'quantum', 'chromodynamics', 'is', '\n', 'presented', 'for', 'the', 'production', 'of', 'massive', 'photon', 'pairs', 'at', 'hadron', 'colliders', '.', 'All', '\n', 'next', '-', 'to', '-', 'leading', 'order', 'perturbative', 'contributions', 'from', 'quark', '-', 'antiquark']

201

In [39]:
df['text_clean'][0]

'Calculation of prompt diphoton production cross sections at Tevatron and\n  LHC energies   A fully differential calculation in perturbative quantum chromodynamics is\npresented for the production of massive photon pairs at hadron colliders. All\nnext-to-leading order perturbative contributions from quark-antiquark,\ngluon-(anti)quark, and gluon-gluon subprocesses are included, as well as\nall-orders resummation of initial-state gluon radiation valid at\nnext-to-next-to-leading logarithmic accuracy. The region of phase space is\nspecified in which the calculation is most reliable. Good agreement is\ndemonstrated with data from the Fermilab Tevatron, and predictions are made for\nmore detailed tests with CDF and DO data. Predictions are shown for\ndistributions of diphoton pairs produced at the energy of the Large Hadron\nCollider (LHC). Distributions of the diphoton pairs from the decay of a Higgs\nboson are contrasted with those produced from QCD processes at the LHC, showing\nthat enhanced sensitivity to the signal can be obtained with judicious\nselection of events.\n'

In [40]:
df['text_clean'] = df['text_clean'].str.lower()

In [41]:
df['text_clean'][0]

'calculation of prompt diphoton production cross sections at tevatron and\n  lhc energies   a fully differential calculation in perturbative quantum chromodynamics is\npresented for the production of massive photon pairs at hadron colliders. all\nnext-to-leading order perturbative contributions from quark-antiquark,\ngluon-(anti)quark, and gluon-gluon subprocesses are included, as well as\nall-orders resummation of initial-state gluon radiation valid at\nnext-to-next-to-leading logarithmic accuracy. the region of phase space is\nspecified in which the calculation is most reliable. good agreement is\ndemonstrated with data from the fermilab tevatron, and predictions are made for\nmore detailed tests with cdf and do data. predictions are shown for\ndistributions of diphoton pairs produced at the energy of the large hadron\ncollider (lhc). distributions of the diphoton pairs from the decay of a higgs\nboson are contrasted with those produced from qcd processes at the lhc, showing\nthat enhanced sensitivity to the signal can be obtained with judicious\nselection of events.\n'

In [43]:
df["text_clean"] = df["text_clean"].str.replace("\n", " ", regex=False)

In [44]:
print(df.loc[0, "text_clean"])

calculation of prompt diphoton production cross sections at tevatron and   lhc energies   a fully differential calculation in perturbative quantum chromodynamics is presented for the production of massive photon pairs at hadron colliders. all next-to-leading order perturbative contributions from quark-antiquark, gluon-(anti)quark, and gluon-gluon subprocesses are included, as well as all-orders resummation of initial-state gluon radiation valid at next-to-next-to-leading logarithmic accuracy. the region of phase space is specified in which the calculation is most reliable. good agreement is demonstrated with data from the fermilab tevatron, and predictions are made for more detailed tests with cdf and do data. predictions are shown for distributions of diphoton pairs produced at the energy of the large hadron collider (lhc). distributions of the diphoton pairs from the decay of a higgs boson are contrasted with those produced from qcd processes at the lhc, showing that enhanced sensitivity to the signal can be obtained with judicious selection of events.

In [45]:
df["text_clean"] = df["text_clean"].str.replace("\t", " ", regex=False)

In [47]:
import re

df["text_clean"] = df["text_clean"].apply(
    lambda x: re.sub(r"\s+", " ", x).strip()
)

In [48]:
print(df.loc[0, "text_clean"])

calculation of prompt diphoton production cross sections at tevatron and lhc energies a fully differential calculation in perturbative quantum chromodynamics is presented for the production of massive photon pairs at hadron colliders. all next-to-leading order perturbative contributions from quark-antiquark, gluon-(anti)quark, and gluon-gluon subprocesses are included, as well as all-orders resummation of initial-state gluon radiation valid at next-to-next-to-leading logarithmic accuracy. the region of phase space is specified in which the calculation is most reliable. good agreement is demonstrated with data from the fermilab tevatron, and predictions are made for more detailed tests with cdf and do data. predictions are shown for distributions of diphoton pairs produced at the energy of the large hadron collider (lhc). distributions of the diphoton pairs from the decay of a higgs boson are contrasted with those produced from qcd processes at the lhc, showing that enhanced sensitivity to the signal can be obtained with judicious selection of events.

In [49]:
df["text_clean"].str.contains(r"https?://", regex=True).sum()

np.int64(3)

In [52]:
df["text_clean"] = df["text_clean"].str.replace(
    r"https?://\S+",
    "",
    regex=True
)

In [50]:
df["text_clean"].str.contains(r"\S+@\S+", regex=True).sum()

np.int64(1)

In [53]:
df["text_clean"] = df["text_clean"].str.replace(
    r"\S+@\S+",
    "",
    regex=True
)

In [54]:
print(df.loc[0, "text_clean"])

calculation of prompt diphoton production cross sections at tevatron and lhc energies a fully differential calculation in perturbative quantum chromodynamics is presented for the production of massive photon pairs at hadron colliders. all next-to-leading order perturbative contributions from quark-antiquark, gluon-(anti)quark, and gluon-gluon subprocesses are included, as well as all-orders resummation of initial-state gluon radiation valid at next-to-next-to-leading logarithmic accuracy. the region of phase space is specified in which the calculation is most reliable. good agreement is demonstrated with data from the fermilab tevatron, and predictions are made for more detailed tests with cdf and do data. predictions are shown for distributions of diphoton pairs produced at the energy of the large hadron collider (lhc). distributions of the diphoton pairs from the decay of a higgs boson are contrasted with those produced from qcd processes at the lhc, showing that enhanced sensitivity to the signal can be obtained with judicious selection of events.

In [56]:
import string
from collections import Counter

text = " ".join(df["text_clean"])

punct = Counter(ch for ch in text if ch in string.punctuation)

punct

Counter({'.': 6046,
         '-': 4589,
         ',': 4531,
         '$': 2507,
         ')': 1506,
         '(': 1492,
         '\\': 1381,
         '_': 800,
         '}': 752,
         '{': 748,
         '^': 668,
         '/': 406,
         "'": 377,
         '=': 364,
         '+': 352,
         ':': 273,
         '"': 185,
         '|': 149,
         '>': 145,
         '`': 133,
         ';': 120,
         '[': 104,
         ']': 103,
         '<': 100,
         '%': 96,
         '~': 91,
         '*': 67,
         '?': 21,
         '&': 11,
         '!': 2})

In [58]:
import re

numbers = re.findall(r"\d+", " ".join(df["text_clean"]))

len(numbers)

4529

In [59]:
Counter(numbers).most_common(20)

[('2', 690),
 ('1', 665),
 ('0', 477),
 ('3', 360),
 ('4', 202),
 ('5', 161),
 ('10', 151),
 ('6', 89),
 ('7', 79),
 ('8', 62),
 ('9', 41),
 ('100', 35),
 ('20', 30),
 ('11', 27),
 ('15', 25),
 ('2005', 23),
 ('12', 23),
 ('18', 22),
 ('30', 21),
 ('13', 20)]

In [60]:
Counter(ch for ch in text if ch in string.punctuation)

Counter({'.': 6046,
         '-': 4589,
         ',': 4531,
         '$': 2507,
         ')': 1506,
         '(': 1492,
         '\\': 1381,
         '_': 800,
         '}': 752,
         '{': 748,
         '^': 668,
         '/': 406,
         "'": 377,
         '=': 364,
         '+': 352,
         ':': 273,
         '"': 185,
         '|': 149,
         '>': 145,
         '`': 133,
         ';': 120,
         '[': 104,
         ']': 103,
         '<': 100,
         '%': 96,
         '~': 91,
         '*': 67,
         '?': 21,
         '&': 11,
         '!': 2})

In [61]:
re.findall(r"\d+", text)

['2004',
 '259000',
 '4',
 '5',
 '4',
 '39',
 '10',
 '22',
 '1',
 '1',
 '4',
 '38',
 '10',
 '22',
 '2',
 '0',
 '1',
 '1',
 '90',
 '2',
 '2',
 '235',
 '0',
 '85',
 '2',
 '51',
 '2',
 '001',
 '260',
 '2',
 '5',
 '5',
 '0',
 '1',
 '2',
 '0',
 '5',
 '5',
 '2',
 '2',
 '3',
 '5',
 '7',
 '0',
 '4',
 '1',
 '2',
 '4',
 '1991',
 '2001',
 '500',
 '600',
 '500',
 '1000',
 '1999',
 '2002',
 '2004',
 '2005',
 '0',
 '2',
 '0',
 '75',
 '1',
 '0',
 '0',
 '0',
 '0',
 '927',
 '0',
 '007',
 '0',
 '012',
 '0',
 '2',
 '0',
 '0',
 '0',
 '727',
 '0',
 '007',
 '0',
 '005',
 '0',
 '007',
 '0',
 '8',
 '5',
 '0',
 '3',
 '5',
 '12',
 '50',
 '150',
 '1',
 '5',
 '8',
 '2',
 '2',
 '4',
 '8',
 '2',
 '4',
 '0',
 '1',
 '1',
 '0',
 '0',
 '30',
 '1',
 '2',
 '3',
 '7',
 '90',
 '100',
 '100',
 '0',
 '1',
 '10',
 '5',
 '0701050',
 '1990',
 '5',
 '1',
 '1',
 '2',
 '2',
 '1',
 '2',
 '3',
 '1',
 '4',
 '160',
 '40',
 '1',
 '05',
 '2',
 '2',
 '64',
 '2',
 '2',
 '0',
 '75',
 '0',
 '07',
 '2',
 '2',
 '0',
 '61',
 '0',
 '04',
 '2',
 '0',
 '2',
 '0',
 '65',
 '0',
 '05',
 '2',
 '0',
 '1',
 '1',
 '2',
 '2',
 '2000',
 '7500',
 '100',
 '100',
 '7',
 '7622',
 '6',
 '72256',
 '7',
 '0',
 '2',
 '3',
 '4',
 '2',
 '3',
 '0',
 '1',
 '0',
 '92',
 '246401',
 '2004',
 '205',
 '013',
 '205',
 '013',
 '7',
 '2',
 '230736',
 '0',
 '000010',
 '0',
 '012',
 '0',
 '021',
 '2',
 '205',
 '013',
 '28',
 '9',
 '1',
 '0',
 '1',
 '28',
 '0',
 '04',
 '0',
 '167',
 '0',
 '006',
 '7',
 '54',
 '0',
 '30',
 '0',
 '0351',
 '0',
 '0014',
 '0',
 '124',
 '0',
 '010',
 '1',
 '04',
 '0',
 '13',
 '205',
 '013',
 '10',
 '500',
 '1',
 '2',
 '10',
 '10',
 '500',
 '76',
 '76',
 '76',
 '1',
 '3',
 '1',
 '4',
 '1',
 '4',
 '1',
 '4',
 '4',
 '2',
 '0',
 '1',
 '2',
 '3',
 '2006',
 '1971',
 '2006',
 '3',
 '0',
 '1',
 '1',
 '2',
 '1',
 '2',
 '1',
 '2',
 '3',
 '4',
 '4',
 '1',
 '2',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '77',
 '1',
 '10',
 '15',
 '3000',
 '4200',
 '5000',
 '5400',
 '4500',
 '7',
 '10',
 '15',
 '10',
 '14',
 '4500',
 '2007',
 '0',
 '6',
 '10',
 '15',
 '1',
 '10',
 '15',
 '248',
 '248',
 '0',
 '1',
 '2',
 '1',
 '1',
 '1968',
 '1974',
 '0',
 '6',
 '6',
 '2',
 '2',
 '4',
 '9',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '4',
 '8',
 '2',
 '4',
 '3',
 '1',
 '2',
 '98',
 '227202',
 '2007',
 '2',
 '3',
 '110',
 '2',
 '3',
 '110',
 '2',
 '2',
 '3',
 '2',
 '3',
 '10',
 '5',
 '2',
 '3',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '4',
 '6',
 '2',
 '1',
 '31',
 '2',
 '44',
 '7',
 '100',
 '1',
 '6',
 '2',
 '2',
 '0',
 '0',
 '0',
 '3770',
 '1',
 '1',
 '6',
 '1',
 '1',
 '0303188',
 '0402640',
 '0703050',
 '2',
 '2',
 '2',
 '2',
 '2',
 '0',
 '0',
 '5',
 '2',
 '0',
 '5',
 '1',
 '7',
 '2',
 '100',
 '100',
 '1',
 '52',
 '67',
 '52',
 '58',
 '67',
 '2',
 '2',
 '2000',
 '2005',
 '2',
 '56',
 '6',
 '2',
 '7',
 '7',
 '1413',
 '117',
 '2',
 '56',
 '5',
 '4',
 '12',
 '7',
 '13',
 '1000',
 '3',
 '7',
 '2',
 '1',
 '2',
 '2',
 '1',
 '94',
 '220401',
 '2005',
 '32',
 '0',
 '9524',
 '5',
 '5',
 '5904',
 '3',
 '47',
 '6752',
 '5',
 '20',
 '40',
 '4',
 '4',
 '0',
 '4',
 '0',
 '0',
 '0',
 '2004',
 '24',
 '2007',
 '4',
 '433',
 '1987',
 '71',
 '012330',
 '2005',
 '1',
 '2',
 '1',
 '2',
 '3',
 '1',
 '3',
 '1',
 '1',
 '2',
 '1',
 '2',
 '1',
 '2',
 '3',
 '0',
 '1',
 '3',
 '0',
 '2',
 '0',
 '1',
 '2',
 '0',
 '3',
 '0',
 '3',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '1',
 '6',
 '0',
 '2',
 '3',
 '4',
 '3',
 '3',
 '3',
 '2',
 '2',
 '2',
 '0',
 '4737',
 '0',
 '3',
 '0',
 '9',
 '0',
 '66',
 '1',
 '2',
 '1',
 '2',
 '1',
 '2',
 '1996',
 '2',
 '2',
 '1',
 '6',
 '1',
 '1',
 '2',
 '2',
 '1',
 '2',
 '2',
 '1',
 '4',
 '5',
 '4',
 '3',
 '2',
 '1',
 '1',
 '0607218',
 '1',
 '2',
 '1',
 '0632',
 '058',
 '1',
 '063258',
 '3',
 '054857',
 '148',
 '3',
 '0634',
 '0521',
 '20',
 '3',
 '2',
 '4',
 '1',
 '2',
 '1',
 '7',
 '25',
 '001',
 '3',
 '20',
 '10',
 '10',
 '10',
 '10',
 '0',
 '23',
 '0',
 '06',
 '300',
 '0',
 '10',
 '0',
 '395',
 '83',
 '23',
 '0',
 '285',
 '300',
 '300',
 '900',
 '1200',
 '1800',
 '300',
 '900',
 '2347',
 '4342',
 '14',
 '2347',
 '4342',
 '2347',
 '4342',
 '23503',
 '4328',
 '2',
 '282',
 '3',
 '59',
 '23500',
 '4319',
 '2',
 '302',
 '8',
 '77',
 '23495',
 '4338',
 '2',
 '690',
 '16',
 '28',
 '2347',
 '4342',
 '23495',
 '4338',
 '23495',
 '4338',
 '25',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '4',
 '4',
 '1',
 '2',
 '3',
 '2',
 '3',
 '6',
 '19',
 '1',
 '8',
 '0',
 '3',
 '1',
 '9',
 '1',
 '2',
 '1',
 '1',
 '2',
 '1',
 '2',
 '1',
 '2',
 '1',
 '2',
 '1',
 '2',
 '1',
 '2',
 '1',
 '2',
 '1',
 '0',
 '3',
 '2',
 '0',
 '4',
 '1',
 '7',
 '6',
 '33',
 '1232',
 '8',
 '3',
 '10',
 '4',
 '3',
 '1',
 '2',
 '0',
 '6',
 '1',
 '2',
 '0',
 '6',
 '0',
 '8',
 '1',
 '7',
 '2',
 '0',
 '1',
 '8',
 '666',
 '2',
 '6',
 '348',
 '348',
 '42',
 '20',
 '0',
 '348',
 '400',
 '348',
 '1',
 '348',
 '348',
 '3',
 '5',
 '1357',
 '6429',
 '1357',
 '6429',
 '7',
 '3',
 '1',
 '4',
 '160',
 '2',
 '5',
 '2',
 '10',
 '1',
 '2',
 '32',
 '1357',
 '6429',
 '3',
 '31',
 '2',
 '10',
 '30',
 '3',
 '1987',
 '1987',
 '1999',
 '2006',
 '2007',
 '1987',
 '1987',
 '1987',
 '20',
 '2007',
 '1987',
 '2',
 '4',
 '10',
 '36',
 '1',
 '0',
 '5',
 '10',
 '0',
 '3',
 '2',
 '1400',
 '1',
 '2004',
 '6000',
 '1',
 '3',
 '2',
 '1',
 '1990',
 '3',
 '0501076',
 '36',
 '1',
 '2012',
 '103',
 '110',
 '5',
 '2012',
 '1209',
 '5993',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '6',
 '328',
 '4',
 '0',
 '2',
 '328',
 '4',
 '0',
 '2',
 '2',
 '328',
 '4',
 '0',
 '2',
 '7',
 '1',
 '4',
 '328',
 '4',
 '0',
 '2',
 '328',
 '4',
 '0',
 '2',
 '0',
 '3',
 '1400',
 '30',
 '2',
 '17',
 '328',
 '4',
 '0',
 '2',
 '328',
 '4',
 '0',
 '2',
 '10000',
 '10',
 '12',
 '10',
 '10',
 '51',
 '5',
 '0',
 '03',
 '3',
 '3',
 '200',
 '2',
 '4',
 '3',
 '3',
 '4',
 '1',
 '2',
 '200',
 '3',
 '2',
 '4',
 '4',
 '2',
 '3783',
 '1',
 '3783',
 '5',
 '3',
 '6',
 '1',
 '27',
 '0',
 '3',
 '10',
 '10',
 '10',
 '7',
 '124',
 '124',
 '107',
 '7472',
 '10537',
 '1991',
 '16',
 '2',
 '85',
 '2006',
 '183',
 '411',
 '2006',
 '0',
 '70',
 '0',
 '75',
 '0',
 '65',
 '1459',
 '7472',
 '10537',
 '1991',
 '16',
 '0703676',
 '2007',
 '5',
 '10',
 '60',
 '1',
 '1',
 '5',
 '2',
 '5',
 '1',
 '1',
 '100',
 '10',
 '100',
 '29',
 '3',
 '1',
 '1',
 '1',
 '2',
 '2',
 '1',
 '2',
 '2',
 '4',
 '1',
 '2',
 '1',
 '4',
 '1',
 '2',
 '4',
 '1',
 '2',
 '1',
 '0',
 '0',
 '0',
 '0',
 '1',
 '2',
 '1',
 '2',
 '2',
 '3',
 '2',
 '2',
 '22',
 '0',
 '0',
 '2',
 '2',
 '1',
 '5',
 '24',
 '70',
 '160',
 '2400',
 '24',
 '100',
 '70',
 '4',
 '160',
 '24',
 '0',
 '50',
 '2',
 '5',
 '3',
 '2',
 '1',
 '3',
 '3',
 '3',
 '2',
 '3',
 '3',
 '3',
 '5440',
 '5440',
 '1',
 '4',
 '950',
 '50',
 '5',
 '0',
 '5',
 '0',
 '1',
 '2',
 '60',
 '60',
 '20',
 '150',
 '2003',
 '61',
 '1',
 '0657',
 '5',
 '1',
 '0657',
 '56',
 '1',
 '0657',
 '56',
 '68',
 '1',
 '25',
 '2',
 '0',
 '7',
 '2',
 ...]

In [63]:
latex_pattern = r"\$.*?\$"

latex_count = df["text_clean"].str.contains(latex_pattern, regex=True).sum()

print(latex_count)

245

In [64]:
latex_examples = df[df["text_clean"].str.contains(latex_pattern, regex=True)]

latex_examples["text_clean"].head(5)

1     sparsity-certifying graph decompositions we de...
4     from dyadic $\lambda_{\alpha}$ to $\lambda_{\a...
5     bosonic characters of atomic cooper pairs acro...
10    computing genus 2 hilbert-siegel modular forms...
11    distribution of integral fourier coefficients ...
Name: text_clean, dtype: str

In [66]:
sample = df.loc[4, "text_clean"]

print(sample)

from dyadic $\lambda_{\alpha}$ to $\lambda_{\alpha}$ in this paper we show how to compute the $\lambda_{\alpha}$ norm, $\alpha\ge 0$, using the dyadic grid. this result is a consequence of the description of the hardy spaces $h^p(r^n)$ in terms of dyadic and special atoms.

In [67]:
import re

def clean_latex(text):
    """
    Remove LaTeX syntax while preserving meaningful words.
    """

    # Remove $
    text = re.sub(r"\$", "", text)

    # Replace common Greek letters
    greek_letters = {
        r"\\alpha": " alpha ",
        r"\\beta": " beta ",
        r"\\gamma": " gamma ",
        r"\\delta": " delta ",
        r"\\lambda": " lambda ",
        r"\\mu": " mu ",
        r"\\sigma": " sigma ",
        r"\\phi": " phi ",
        r"\\psi": " psi ",
        r"\\omega": " omega ",
        r"\\theta": " theta ",
        r"\\pi": " pi "
    }

    for latex, word in greek_letters.items():
        text = re.sub(latex, word, text)

    # Remove remaining backslashes
    text = re.sub(r"\\", " ", text)

    # Remove braces
    text = re.sub(r"[{}]", " ", text)

    # Replace underscore with space
    text = re.sub(r"_", " ", text)

    # Remove ^
    text = re.sub(r"\^", " ", text)

    # Remove multiple spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [ ]:
sample_clean = clean_latex()

print(sample_clean)

from dyadic lambda alpha to lambda alpha in this paper we show how to compute the lambda alpha norm, alpha ge 0, using the dyadic grid. this result is a consequence of the description of the hardy spaces h p(r n) in terms of dyadic and special atoms.

In [69]:
print("="*100)
print("ORIGINAL\n")
print(sample)

print("\n" + "="*100)

print("CLEANED\n")
print(sample_clean)

====================================================================================================
ORIGINAL

from dyadic $\lambda_{\alpha}$ to $\lambda_{\alpha}$ in this paper we show how to compute the $\lambda_{\alpha}$ norm, $\alpha\ge 0$, using the dyadic grid. this result is a consequence of the description of the hardy spaces $h^p(r^n)$ in terms of dyadic and special atoms.

====================================================================================================
CLEANED

from dyadic lambda alpha to lambda alpha in this paper we show how to compute the lambda alpha norm, alpha ge 0, using the dyadic grid. this result is a consequence of the description of the hardy spaces h p(r n) in terms of dyadic and special atoms.

In [70]:
remaining = re.findall(r"\$|\\|{|}|\^|_", sample_clean)

print(remaining)

[]

In [71]:
sample = df.loc[4, "text_clean"]

print(sample)

from dyadic $\lambda_{\alpha}$ to $\lambda_{\alpha}$ in this paper we show how to compute the $\lambda_{\alpha}$ norm, $\alpha\ge 0$, using the dyadic grid. this result is a consequence of the description of the hardy spaces $h^p(r^n)$ in terms of dyadic and special atoms.

In [73]:
from nltk.tokenize import word_tokenize

nltk_tokens = word_tokenize(sample_clean)

print(nltk_tokens[:80])
print("Total Tokens :", len(nltk_tokens))

['from', 'dyadic', 'lambda', 'alpha', 'to', 'lambda', 'alpha', 'in', 'this', 'paper', 'we', 'show', 'how', 'to', 'compute', 'the', 'lambda', 'alpha', 'norm', ',', 'alpha', 'ge', '0', ',', 'using', 'the', 'dyadic', 'grid', '.', 'this', 'result', 'is', 'a', 'consequence', 'of', 'the', 'description', 'of', 'the', 'hardy', 'spaces', 'h', 'p', '(', 'r', 'n', ')', 'in', 'terms', 'of', 'dyadic', 'and', 'special', 'atoms', '.']
Total Tokens : 55

In [74]:
doc = nlp(sample_clean)

spacy_tokens = [token.text for token in doc]

print(spacy_tokens[:80])
print("Total Tokens :", len(spacy_tokens))

['from', 'dyadic', 'lambda', 'alpha', 'to', 'lambda', 'alpha', 'in', 'this', 'paper', 'we', 'show', 'how', 'to', 'compute', 'the', 'lambda', 'alpha', 'norm', ',', 'alpha', 'ge', '0', ',', 'using', 'the', 'dyadic', 'grid', '.', 'this', 'result', 'is', 'a', 'consequence', 'of', 'the', 'description', 'of', 'the', 'hardy', 'spaces', 'h', 'p(r', 'n', ')', 'in', 'terms', 'of', 'dyadic', 'and', 'special', 'atoms', '.']
Total Tokens : 53

In [76]:
sample_clean

'from dyadic lambda alpha to lambda alpha in this paper we show how to compute the lambda alpha norm, alpha ge 0, using the dyadic grid. this result is a consequence of the description of the hardy spaces h p(r n) in terms of dyadic and special atoms.'

In [77]:
doc = nlp(sample_clean)

tokens = [
    token.text
    for token in doc
    if not token.is_stop and not token.is_punct
]

print(tokens)
print(len(tokens))

['dyadic', 'lambda', 'alpha', 'lambda', 'alpha', 'paper', 'compute', 'lambda', 'alpha', 'norm', 'alpha', 'ge', '0', 'dyadic', 'grid', 'result', 'consequence', 'description', 'hardy', 'spaces', 'h', 'p(r', 'n', 'terms', 'dyadic', 'special', 'atoms']
27

In [ ]:
custom_stopwords = {
    "paper",
    "method",
    "methods",
    "result",
    "results",
    "using",
    "use",
    "propose",
    "proposed",
    "present",
    "presented",
    "show",
    "shown",
    "approach",
    "based",
    "work",
    "study"
}

In [78]:
from collections import Counter

all_tokens = []

for text in df["text_clean"]:

    doc = nlp(text)

    tokens = [
        token.text.lower()
        for token in doc
        if not token.is_stop
        and not token.is_punct
    ]

    all_tokens.extend(tokens)

word_freq = Counter(all_tokens)

word_freq.most_common(50)

[('$', 1253),
 ('model', 412),
 ('field', 317),
 ('results', 312),
 ('quantum', 290),
 ('energy', 284),
 ('theory', 253),
 ('mass', 238),
 ('spin', 235),
 ('time', 234),
 ('data', 217),
 ('non', 208),
 ('new', 206),
 ('high', 205),
 ('present', 201),
 ('state', 196),
 ('study', 193),
 ('density', 192),
 ('phase', 191),
 ('function', 188),
 ('based', 181),
 ('system', 180),
 ('order', 175),
 ('find', 175),
 ('type', 175),
 ('large', 173),
 ('x', 171),
 ('emission', 168),
 ('space', 166),
 ('paper', 165),
 ('states', 163),
 ('properties', 161),
 ('magnetic', 159),
 ('dimensional', 157),
 ('low', 157),
 ('analysis', 157),
 ('structure', 155),
 ('systems', 149),
 ('observed', 143),
 ('=', 143),
 ('star', 140),
 ('number', 139),
 ('different', 137),
 ('ray', 137),
 ('1', 135),
 ('temperature', 135),
 ('+', 133),
 ('observations', 130),
 ('models', 127),
 ('evolution', 125)]

In [79]:
custom_stopwords = {
    "paper",
    "study",
    "present",
    "presented",
    "results",
    "result",
    "show",
    "shown",
    "using",
    "based",
    "find",
    "found",
    "propose",
    "proposed",
    "approach"
}

In [80]:
latex_rows = df[df["text_clean"].str.contains(r"\$", regex=True)]

print(latex_rows.shape)

latex_rows["text_clean"].head(5)

(247, 9)

1     sparsity-certifying graph decompositions we de...
4     from dyadic $\lambda_{\alpha}$ to $\lambda_{\a...
5     bosonic characters of atomic cooper pairs acro...
10    computing genus 2 hilbert-siegel modular forms...
11    distribution of integral fourier coefficients ...
Name: text_clean, dtype: str

In [81]:
df["text_clean"] = df["text_clean"].apply(clean_latex)

In [82]:
latex_pattern = r"\$"

remaining = df["text_clean"].str.contains(latex_pattern, regex=True).sum()

print(f"Remaining rows with $ : {remaining}")

Remaining rows with $ : 0

In [83]:
special_chars = ["\\", "{", "}", "_", "^"]

for ch in special_chars:
    count = df["text_clean"].str.contains(re.escape(ch), regex=True).sum()
    print(f"{ch} : {count}")

\ : 0
{ : 0
} : 0
_ : 0
^ : 0

In [84]:
from collections import Counter

all_tokens = []

for text in df["text_clean"]:
    doc = nlp(text)

    tokens = [
        token.text.lower()
        for token in doc
        if not token.is_stop
        and not token.is_punct
    ]

    all_tokens.extend(tokens)

word_freq = Counter(all_tokens)

word_freq.most_common(50)

[('model', 412),
 ('field', 317),
 ('results', 312),
 ('quantum', 290),
 ('energy', 284),
 ('2', 256),
 ('theory', 253),
 ('mass', 238),
 ('x', 235),
 ('spin', 235),
 ('time', 234),
 ('data', 217),
 ('non', 208),
 ('high', 207),
 ('new', 206),
 ('+', 202),
 ('present', 201),
 ('state', 197),
 ('n', 197),
 ('1', 195),
 ('study', 193),
 ('density', 192),
 ('d', 191),
 ('phase', 190),
 ('function', 189),
 ('based', 181),
 ('system', 180),
 ('=', 180),
 ('type', 176),
 ('order', 175),
 ('find', 175),
 ('large', 173),
 ('k', 168),
 ('emission', 168),
 ('m', 167),
 ('space', 166),
 ('paper', 165),
 ('states', 163),
 ('properties', 161),
 ('low', 159),
 ('magnetic', 159),
 ('dimensional', 157),
 ('analysis', 157),
 ('structure', 157),
 ('systems', 149),
 ('s', 144),
 ('observed', 143),
 ('star', 142),
 ('number', 139),
 ('different', 137)]

In [85]:
import re

custom_stopwords = {
    "paper",
    "study",
    "results",
    "result",
    "present",
    "presented",
    "based",
    "find",
    "found",
    "new",
    "show",
    "shown",
    "using",
    "approach",
    "proposed",
    "propose"
}

def preprocess_ml(text):

    doc = nlp(text)

    tokens = []

    for token in doc:

        word = token.lemma_.lower()

        # Remove stopwords
        if token.is_stop:
            continue

        # Remove punctuation
        if token.is_punct:
            continue

        # Remove numbers
        if token.like_num:
            continue

        # Remove one-letter words
        if len(word) == 1:
            continue

        # Remove custom stopwords
        if word in custom_stopwords:
            continue

        tokens.append(word)

    return " ".join(tokens)

In [86]:
df["text_ml"] = df["text_clean"].apply(preprocess_ml)

In [87]:
df["text_ml"]

0      calculation prompt diphoton production cross s...
1      sparsity certify graph decomposition describe ...
2      evolution earth moon system base dark matter f...
3      determinant stirling cycle number count unlabe...
4      dyadic lambda alpha lambda alpha compute lambd...
                             ...
995    brane world black ring dimensional neutral rot...
996    stable algebra entire function suppose belong ...
997    test vector trilinear form representation unra...
998    generic character sheave disconnected group ch...
999    measurement d0 d0bar mix d0->ks pi+ pi- decay ...
Name: text_ml, Length: 1000, dtype: str

In [88]:
df["text_clean"]

0      calculation of prompt diphoton production cros...
1      sparsity-certifying graph decompositions we de...
2      the evolution of the earth-moon system based o...
3      a determinant of stirling cycle numbers counts...
4      from dyadic lambda alpha to lambda alpha in th...
                             ...
995    brane world black rings five dimensional neutr...
996    stable algebras of entire functions suppose th...
997    test vectors for trilinear forms, when two rep...
998    generic character sheaves on disconnected grou...
999    measurement of d0-d0bar mixing in d0->ks pi+ p...
Name: text_clean, Length: 1000, dtype: str

In [89]:
df["text_ml"].isnull().sum()

np.int64(0)

In [90]:
(df["text_ml"].str.len() == 0).sum()

np.int64(0)

In [92]:
comparison = pd.DataFrame({
    "Original": df["text_clean"].str.split().str.len(),
    "ML": df["text_ml"].str.split().str.len()
})

comparison.describe()

          Original           ML
count  1000.000000  1000.000000
mean    133.123000    73.771000
std      65.036156    35.172769
min      11.000000     7.000000
25%      86.000000    49.000000
50%     120.000000    68.000000
75%     171.000000    93.250000
max     325.000000   180.000000

In [93]:
from collections import Counter

words = " ".join(df["text_ml"]).split()

Counter(words).most_common(30)

[('model', 565),
 ('field', 404),
 ('state', 364),
 ('system', 328),
 ('energy', 323),
 ('function', 308),
 ('time', 302),
 ('quantum', 290),
 ('theory', 290),
 ('mass', 280),
 ('high', 261),
 ('star', 255),
 ('spin', 251),
 ('equation', 236),
 ('phase', 229),
 ('low', 225),
 ('density', 219),
 ('large', 217),
 ('type', 216),
 ('effect', 212),
 ('non', 208),
 ('order', 207),
 ('space', 207),
 ('datum', 201),
 ('structure', 200),
 ('particle', 193),
 ('base', 192),
 ('property', 185),
 ('galaxy', 184),
 ('line', 181)]

In [94]:
df.head()

,id,title,abstract,authors,categories,update_date,category,text_raw,text_clean,text_ml
0,704.0001,Calculation of prompt diphoton production cros...,A fully differential calculation in perturba...,"C. Bal\'azs, E. L. Berger, P. M. Nadolsky, C.-...",hep-ph,2008-11-26,hep-ph,Calculation of prompt diphoton production cros...,calculation of prompt diphoton production cros...,calculation prompt diphoton production cross s...
1,704.0002,Sparsity-certifying Graph Decompositions,"We describe a new algorithm, the $(k,\ell)$-...",Ileana Streinu and Louis Theran,math.CO cs.CG,2008-12-13,math.CO,Sparsity-certifying Graph Decompositions We ...,sparsity-certifying graph decompositions we de...,sparsity certify graph decomposition describe ...
2,704.0003,The evolution of the Earth-Moon system based o...,The evolution of Earth-Moon system is descri...,Hongjun Pan,physics.gen-ph,2008-01-13,physics.gen-ph,The evolution of the Earth-Moon system based o...,the evolution of the earth-moon system based o...,evolution earth moon system base dark matter f...
3,704.0004,A determinant of Stirling cycle numbers counts...,We show that a determinant of Stirling cycle...,David Callan,math.CO,2007-05-23,math.CO,A determinant of Stirling cycle numbers counts...,a determinant of stirling cycle numbers counts...,determinant stirling cycle number count unlabe...
4,704.0005,From dyadic $\Lambda_{\alpha}$ to $\Lambda_{\a...,In this paper we show how to compute the $\L...,Wael Abu-Shammala and Alberto Torchinsky,math.CA math.FA,2013-10-15,math.CA,From dyadic $\Lambda_{\alpha}$ to $\Lambda_{\a...,from dyadic lambda alpha to lambda alpha in th...,dyadic lambda alpha lambda alpha compute lambd...

In [95]:
df["category"].value_counts().head(20)

category
astro-ph              188
hep-th                 63
hep-ph                 60
quant-ph               52
cond-mat.mes-hall      42
cond-mat.str-el        39
gr-qc                  34
cond-mat.mtrl-sci      32
cond-mat.stat-mech     25
cond-mat.supr-con      25
nucl-th                21
math.PR                20
physics.optics         20
math.CO                19
cond-mat.other         18
math.AG                17
hep-ex                 15
cs.IT                  15
math.AP                15
nucl-ex                15
Name: count, dtype: int64

In [99]:
processed_df = df[
    [
        "id",
        "title",
        "authors",
        "category",
        "text_raw",
        "text_ml"
    ]
]

In [96]:
import os

os.makedirs("../data/processed", exist_ok=True)

df.to_parquet(
    "../data/processed/arxiv_ml.parquet",
    index=False
)

In [98]:
df.shape

(1000, 10)

In [100]:
processed_df.to_parquet(
    "../data/processed/arxiv_ml.parquet",
    index=False
)