In [1]:
# from google.colab import drive

In [2]:
# drive.mount('/content/drive')

In [3]:
# import json
# import pandas as pd
# import io
# import csv
# import psycopg2

# JSON_PATH = 'C:/Users/hp/Documents/arxiv-metadata-oai-snapshot.json'
# PARQUET_PATH = 'C:/Users/hp/Documents/arxiv_raw.parquet'

# # ---------- STEP 1: Read raw JSON lines into a DataFrame ----------
# KEEP_FIELDS = {'id', 'title', 'abstract', 'categories'}
# records = []
# with open(JSON_PATH, 'r', encoding='utf-8') as f:
#     for line in f:
#         obj = json.loads(line)
#         records.append({k: obj.get(k) for k in KEEP_FIELDS})

# df = pd.DataFrame(records)
# del records
# print(f"Loaded {len(df):,} rows from JSON")

# # Drop duplicate ids in the source itself, just in case
# df = df.drop_duplicates(subset=['id']).reset_index(drop=True)
# print(f"After deduping source ids: {len(df):,} rows")

# # ---------- STEP 2: Save as Parquet ----------
# df.to_parquet(PARQUET_PATH, index=False)
# print(f"Saved to {PARQUET_PATH}")

# # ---------- STEP 3: Load into Postgres safely (skip existing/duplicate ids) ----------
# df = pd.read_parquet(PARQUET_PATH)

# DB_PARAMS = {
#     'dbname': 'arxiv_db',
#     'user': 'postgres',
#     'password': 'Dex@ter69',
#     'host': 'localhost',
#     'port': 5432,
# }

# BATCH_SIZE = 50_000

# conn = psycopg2.connect(**DB_PARAMS)
# cur = conn.cursor()

# # Create a staging table with the same structure, no constraints
# cur.execute("""
#     DROP TABLE IF EXISTS arxiv_papers_staging;
#     CREATE TABLE arxiv_papers_staging (
#         id TEXT,
#         title TEXT,
#         abstract TEXT,
#         categories TEXT
#     );
# """)
# conn.commit()

# def load_batch_to_staging(batch_df):
#     buffer = io.StringIO()
#     writer = csv.writer(buffer)
#     for _, row in batch_df.iterrows():
#         writer.writerow([row['id'], row['title'], row['abstract'], row['categories']])
#     buffer.seek(0)
#     cur.copy_expert(
#         "COPY arxiv_papers_staging (id, title, abstract, categories) FROM STDIN WITH CSV",
#         buffer
#     )

# total_loaded = 0
# for start in range(0, len(df), BATCH_SIZE):
#     batch_df = df.iloc[start:start + BATCH_SIZE]
#     load_batch_to_staging(batch_df)
#     conn.commit()
#     total_loaded += len(batch_df)
#     print(f"Staged {total_loaded:,} rows...")

# print(f"Done staging. Total rows staged: {total_loaded:,}")

# # Move from staging into the real table, skipping duplicates
# cur.execute("""
#     INSERT INTO arxiv_papers (id, title, abstract, categories)
#     SELECT DISTINCT ON (id) id, title, abstract, categories
#     FROM arxiv_papers_staging
#     ON CONFLICT (id) DO NOTHING;
# """)
# conn.commit()

# cur.execute("SELECT COUNT(*) FROM arxiv_papers;")
# final_count = cur.fetchone()[0]
# print(f"Final row count in arxiv_papers: {final_count:,}")

# # Clean up staging table
# cur.execute("DROP TABLE arxiv_papers_staging;")
# conn.commit()

# cur.close()
# conn.close()

In [ ]:
# import pandas as pd
# from sqlalchemy import create_engine
# from urllib.parse import quote_plus
# # build connection string (password URL-encoded because it contains '@')
# password = quote_plus("Dex@ter69")   # replace with your real password
# DB_URL = f"postgresql://postgres:{password}@localhost:5432/arxiv_db"

# engine = create_engine(DB_URL)

# # Load full table
# df = pd.read_sql("SELECT id, title, abstract, categories FROM arxiv_papers", engine)
# print(f"Loaded {len(df):,} rows from Postgres")

# # Sample 3 lakh (300,000) rows with fixed random_state for reproducibility
# SAMPLE_SIZE = 300_000
# df = df.sample(n=SAMPLE_SIZE, random_state=42).reset_index(drop=True)

# print(f"Sampled {len(df):,} rows")
# df.head()

Loaded 3,113,242 rows from Postgres
Sampled 300,000 rows

,id,title,abstract,categories
0,1304.6233,A Counterexample for the Validity of Using Nuc...,Rank minimization has attracted a lot of att...,stat.ML math.OC
1,2103.09484,RIS-Aided Next-Generation High-Speed Train Com...,High-speed train (HST) communication is a ve...,cs.IT math.IT
2,1710.01664,Nonlinear theory of transverse beam echoes,Transverse beam echoes can be excited with a...,physics.acc-ph
3,1706.05111,A Mixture Model for Learning Multi-Sense Word ...,Word embeddings are now a standard technique...,cs.CL
4,2512.16090,Low Regularity Well-Posedness of Cauchy Proble...,"In this article, we initiate the study of the ...",math.AP

In [ ]:
# # save this sample as a Parquet checkpoint so we never need to re-query Postgres for this exact sample
# SAMPLE_PARQUET_PATH = 'C:/Users/hp/Documents/arxiv_sample_300k.parquet'
# df.to_parquet(SAMPLE_PARQUET_PATH, index=False)
# print(f"Saved 300k sample to {SAMPLE_PARQUET_PATH}")

# df.head()

Saved 300k sample to C:/Users/hp/Documents/arxiv_sample_300k.parquet

,id,title,abstract,categories
0,1304.6233,A Counterexample for the Validity of Using Nuc...,Rank minimization has attracted a lot of att...,stat.ML math.OC
1,2103.09484,RIS-Aided Next-Generation High-Speed Train Com...,High-speed train (HST) communication is a ve...,cs.IT math.IT
2,1710.01664,Nonlinear theory of transverse beam echoes,Transverse beam echoes can be excited with a...,physics.acc-ph
3,1706.05111,A Mixture Model for Learning Multi-Sense Word ...,Word embeddings are now a standard technique...,cs.CL
4,2512.16090,Low Regularity Well-Posedness of Cauchy Proble...,"In this article, we initiate the study of the ...",math.AP

In [2]:
# import pandas
import pandas as pd

# load the previously saved 300k sample directly from Parquet — much faster than querying Postgres again
SAMPLE_PARQUET_PATH = 'C:/Users/hp/Documents/arxiv_sample_300k.parquet'
df = pd.read_parquet(SAMPLE_PARQUET_PATH)

print(f"Loaded {len(df):,} rows from Parquet checkpoint")
df.head()

Loaded 300,000 rows from Parquet checkpoint

,id,title,abstract,categories
0,1304.6233,A Counterexample for the Validity of Using Nuc...,Rank minimization has attracted a lot of att...,stat.ML math.OC
1,2103.09484,RIS-Aided Next-Generation High-Speed Train Com...,High-speed train (HST) communication is a ve...,cs.IT math.IT
2,1710.01664,Nonlinear theory of transverse beam echoes,Transverse beam echoes can be excited with a...,physics.acc-ph
3,1706.05111,A Mixture Model for Learning Multi-Sense Word ...,Word embeddings are now a standard technique...,cs.CL
4,2512.16090,Low Regularity Well-Posedness of Cauchy Proble...,"In this article, we initiate the study of the ...",math.AP

In [7]:
df.head()

,id,title,abstract,categories
0,1304.6233,A Counterexample for the Validity of Using Nuc...,Rank minimization has attracted a lot of att...,stat.ML math.OC
1,2103.09484,RIS-Aided Next-Generation High-Speed Train Com...,High-speed train (HST) communication is a ve...,cs.IT math.IT
2,1710.01664,Nonlinear theory of transverse beam echoes,Transverse beam echoes can be excited with a...,physics.acc-ph
3,1706.05111,A Mixture Model for Learning Multi-Sense Word ...,Word embeddings are now a standard technique...,cs.CL
4,2512.16090,Low Regularity Well-Posedness of Cauchy Proble...,"In this article, we initiate the study of the ...",math.AP

#

In [3]:
df.head()

,id,title,abstract,categories
0,1304.6233,A Counterexample for the Validity of Using Nuc...,Rank minimization has attracted a lot of att...,stat.ML math.OC
1,2103.09484,RIS-Aided Next-Generation High-Speed Train Com...,High-speed train (HST) communication is a ve...,cs.IT math.IT
2,1710.01664,Nonlinear theory of transverse beam echoes,Transverse beam echoes can be excited with a...,physics.acc-ph
3,1706.05111,A Mixture Model for Learning Multi-Sense Word ...,Word embeddings are now a standard technique...,cs.CL
4,2512.16090,Low Regularity Well-Posedness of Cauchy Proble...,"In this article, we initiate the study of the ...",math.AP

In [4]:
# Check missing values
print("Missing values:")
print(df[['title', 'abstract', 'categories']].isna().sum())

# Drop rows missing title, abstract, or categories — these are unusable for training
df = df.dropna(subset=['title', 'abstract', 'categories']).copy()

# Drop duplicate papers (same title+abstract combo)
df = df.drop_duplicates(subset=['title', 'abstract']).reset_index(drop=True)

print(f"Rows after cleaning: {len(df):,}")

Missing values:
title         0
abstract      0
categories    0
dtype: int64
Rows after cleaning: 299,997

In [10]:
df.tail()

,id,title,abstract,categories
299992,2512.22276,Discrete equations and auto-traveling kinks of...,We study the $\phi^{6}$ model and derive two b...,nlin.PS cond-mat.stat-mech math-ph math.MP
299993,2508.13519,Charge Ordering and Magnetic Exchange in the L...,The low-temperature electronic and magnetic pr...,cond-mat.str-el cond-mat.mtrl-sci
299994,2504.08151,Adaptive Bounded Exploration and Intermediate ...,The performance of algorithmic decision rule...,cs.LG
299995,1904.00779,Relation between $f$-vectors and $d$-vectors i...,"We study $f$-vectors, which are the maximal ...",math.RA math.CO math.RT
299996,2604.08894,Ge$^\text{2}$mS-T: Multi-Dimensional Grouping ...,Spiking Neural Networks (SNNs) offer superior ...,cs.NE cs.AI cs.CV

In [5]:
df['categories'].nunique()

22934

In [6]:
#check unique values
df['categories'].unique()

<ArrowStringArray>
[                                'stat.ML math.OC',
                                   'cs.IT math.IT',
                                  'physics.acc-ph',
                                           'cs.CL',
                                         'math.AP',
                         'math.PR math-ph math.MP',
                              'cond-mat.quant-gas',
                                           'cs.AI',
                                        'quant-ph',
                      'cond-mat.mes-hall quant-ph',
 ...
                           'math.DG gr-qc math.DS',
         'q-bio.BM cond-mat.dis-nn physics.bio-ph',
                 'nucl-th hep-ph physics.plasm-ph',
                      'q-fin.MF q-fin.ST q-fin.TR',
                   'math.PR cs.NA math.DS math.NA',
 'cond-mat.mtrl-sci cs.LG physics.data-an stat.ML',
                                'q-fin.MF math.LO',
                    'nlin.AO cs.LG physics.bio-ph',
                'q-fin.ST physics.soc-ph q-fin.PM',
      'nlin.PS cond-mat.stat-mech math-ph math.MP']
Length: 22934, dtype: str

##category merging with same domain

In [7]:
# Extract broad category prefixes (multi-label)
def extract_broad_categories(cat_string: str) -> list:
    tags = cat_string.split()
    broad = set()
    for tag in tags:
        prefix = tag.split('.')[0]  # e.g. cond-mat.str-el -> cond-mat
        broad.add(prefix)
    return sorted(broad)

df['broad_categories'] = df['categories'].apply(extract_broad_categories)

# Aggregate counts — this is the small, shareable summary
from collections import Counter

label_counts = Counter(cat for cats in df['broad_categories'] for cat in cats)
label_counts_df = (
    pd.DataFrame(label_counts.items(), columns=['broad_category', 'count'])
    .sort_values('count', ascending=False)
    .reset_index(drop=True)
)

print(f"Number of unique broad categories: {len(label_counts_df)}")
print(label_counts_df.to_string())

Number of unique broad categories: 36
   broad_category  count
0              cs  94182
1            math  73994
2        cond-mat  41132
3        astro-ph  37339
4         physics  29991
5          hep-ph  19220
6          hep-th  17751
7        quant-ph  17745
8            stat  14532
9            eess  12921
10          gr-qc  11920
11        math-ph   8869
12        nucl-th   6129
13         hep-ex   5950
14          q-bio   5455
15           nlin   4585
16        hep-lat   3005
17        nucl-ex   2822
18          q-fin   2463
19           econ   1563
20       chao-dyn    229
21          q-alg    140
22       solv-int    128
23       alg-geom    117
24         cmp-lg     77
25          dg-ga     71
26       patt-sol     61
27       adap-org     54
28       funct-an     40
29        mtrl-th     21
30        chem-ph     21
31       comp-gas     20
32       supr-con     15
33        atom-ph     11
34       acc-phys      5
35         ao-sci      2

In [8]:
# Map legacy/deprecated arXiv category names to their modern broad equivalents
LEGACY_MAP = {
    'chao-dyn': 'nlin',
    'q-alg': 'math',
    'alg-geom': 'math',
    'solv-int': 'nlin',
    'cmp-lg': 'cs',
    'patt-sol': 'nlin',
    'dg-ga': 'math',
    'adap-org': 'nlin',
    'funct-an': 'math',
    'mtrl-th': 'cond-mat',
    'comp-gas': 'nlin',
    'chem-ph': 'physics',
    'supr-con': 'cond-mat',
    'atom-ph': 'physics',
    'plasm-ph': 'physics',
    'acc-phys': 'physics',
    'ao-sci': 'physics',
    'bayes-an': 'physics',   # corrected — was wrongly 'stat'
}

def remap_broad_categories(cats: list) -> list:
    remapped = {LEGACY_MAP.get(c, c) for c in cats}
    return sorted(remapped)

df['broad_categories'] = df['broad_categories'].apply(remap_broad_categories)

# Recount after remapping
from collections import Counter
label_counts = Counter(cat for cats in df['broad_categories'] for cat in cats)
label_counts_df = (
    pd.DataFrame(label_counts.items(), columns=['broad_category', 'count'])
    .sort_values('count', ascending=False)
    .reset_index(drop=True)
)
print(f"Number of unique broad categories after remapping: {len(label_counts_df)}")
print(label_counts_df.to_string())

Number of unique broad categories after remapping: 20
   broad_category  count
0              cs  94182
1            math  73995
2        cond-mat  41132
3        astro-ph  37339
4         physics  30002
5          hep-ph  19220
6          hep-th  17751
7        quant-ph  17745
8            stat  14532
9            eess  12921
10          gr-qc  11920
11        math-ph   8869
12        nucl-th   6129
13         hep-ex   5950
14          q-bio   5455
15           nlin   4585
16        hep-lat   3005
17        nucl-ex   2822
18          q-fin   2463
19           econ   1563

In [9]:
  # Build multi-hot label matrix
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()
Y = mlb.fit_transform(df['broad_categories'])
label_names = mlb.classes_

print("Label matrix shape:", Y.shape)
print("Classes:", label_names)

Label matrix shape: (299997, 20)
Classes: ['astro-ph' 'cond-mat' 'cs' 'econ' 'eess' 'gr-qc' 'hep-ex' 'hep-lat'
 'hep-ph' 'hep-th' 'math' 'math-ph' 'nlin' 'nucl-ex' 'nucl-th' 'physics'
 'q-bio' 'q-fin' 'quant-ph' 'stat']

In [16]:
df.head()

,id,title,abstract,categories,broad_categories
0,1304.6233,A Counterexample for the Validity of Using Nuc...,Rank minimization has attracted a lot of att...,stat.ML math.OC,"[math, stat]"
1,2103.09484,RIS-Aided Next-Generation High-Speed Train Com...,High-speed train (HST) communication is a ve...,cs.IT math.IT,"[cs, math]"
2,1710.01664,Nonlinear theory of transverse beam echoes,Transverse beam echoes can be excited with a...,physics.acc-ph,[physics]
3,1706.05111,A Mixture Model for Learning Multi-Sense Word ...,Word embeddings are now a standard technique...,cs.CL,[cs]
4,2512.16090,Low Regularity Well-Posedness of Cauchy Proble...,"In this article, we initiate the study of the ...",math.AP,[math]

# NLP Preprocessing

In [10]:
import re
import string
import contractions
import emoji
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def to_lowercase(text):
    return text.lower()

def remove_urls(text):
    return re.sub(r'https?://\S+|www\.\S+', '', text)

def remove_html_tags(text):
    return re.sub(r'<.*?>', '', text)

def expand_contractions(text):
    return contractions.fix(text)

def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))

def remove_numbers(text):
    return re.sub(r'\d+', '', text)

def remove_emojis_special_chars(text):
    text = emoji.replace_emoji(text, replace='')
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    return text

def tokenize(text):
    return word_tokenize(text)

def remove_stopwords(tokens):
    return [t for t in tokens if t not in stop_words]

def lemmatize(tokens):
    return [lemmatizer.lemmatize(t) for t in tokens]

def join_tokens(tokens):
    return ' '.join(tokens)

def preprocess_text(text):
    text = to_lowercase(text)
    text = remove_urls(text)
    text = remove_html_tags(text)
    text = expand_contractions(text)
    text = remove_punctuation(text)
    text = remove_numbers(text)
    text = remove_emojis_special_chars(text)
    tokens = tokenize(text)
    tokens = remove_stopwords(tokens)
    tokens = lemmatize(tokens)
    return join_tokens(tokens)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [13]:
df['text'] = (df['title'].fillna('') + ' ' + df['abstract'].fillna('')).apply(preprocess_text)

df[['title', 'text']].head(3)

,title,text
0,A Counterexample for the Validity of Using Nuc...,counterexample validity using nuclear norm con...
1,RIS-Aided Next-Generation High-Speed Train Com...,risaided nextgeneration highspeed train commun...
2,Nonlinear theory of transverse beam echoes,nonlinear theory transverse beam echo transver...

In [ ]:
# import required libraries
import spacy
from nltk.tokenize import word_tokenize
import pandas as pd
import time

# load spaCy's small English model, disabling parser/ner since we only need tokenization
# (this makes spaCy much faster since it skips work we don't need)
nlp = spacy.load('en_core_web_sm', disable=['parser', 'ner'])

# take a sample of documents to compare on (running on all 300k would be slow just for a comparison)
SAMPLE_SIZE = 1000
sample_texts = df['text'].iloc[:SAMPLE_SIZE].tolist()   # using already-cleaned text column

# ---------- NLTK tokenization + timing ----------
start_time = time.time()                                 # record start time
nltk_token_counts = []                                    # will hold token count per document

for doc in sample_texts:                                  # loop through each document
    tokens = word_tokenize(doc)                            # tokenize using NLTK
    nltk_token_counts.append(len(tokens))                  # store number of tokens for this doc

nltk_time = time.time() - start_time                       # total time taken by NLTK

# ---------- spaCy tokenization + timing ----------
start_time = time.time()                                   # reset start time
spacy_token_counts = []                                    # will hold token count per document

# nlp.pipe() processes documents in a batch, much faster than looping nlp(doc) one at a time
for doc in nlp.pipe(sample_texts, batch_size=50):
    spacy_token_counts.append(len(doc))                     # len(doc) gives token count in spaCy

spacy_time = time.time() - start_time                       # total time taken by spaCy

# ---------- build comparison dataframe ----------
comparison_df = pd.DataFrame({
    'nltk_token_count': nltk_token_counts,
    'spacy_token_count': spacy_token_counts,
})

# ---------- print summary stats ----------
print(f"Sample size: {SAMPLE_SIZE} documents")
print()
print(f"NLTK  - Avg tokens/doc: {comparison_df['nltk_token_count'].mean():.2f} | Total time: {nltk_time:.2f}s")
print(f"spaCy - Avg tokens/doc: {comparison_df['spacy_token_count'].mean():.2f} | Total time: {spacy_time:.2f}s")
print()
print("Per-document comparison (first 10 rows):")
print(comparison_df.head(10))

Sample size: 1000 documents

NLTK  - Avg tokens/doc: 98.44 | Total time: 0.55s
spaCy - Avg tokens/doc: 98.44 | Total time: 11.15s

Per-document comparison (first 10 rows):
   nltk_token_count  spacy_token_count
0                95                 95
1                89                 89
2                90                 90
3                52                 52
4               145                145
5                62                 62
6               109                109
7                82                 82
8                74                 74
9                73                 73

TypeError: only integer scalar arrays can be converted to a scalar index

In [14]:
##to be deleted after this run

# force plain numpy/object arrays instead of pyarrow-backed arrays before splitting
from sklearn.model_selection import train_test_split
import numpy as np

# .astype(str) + .to_numpy() guarantees a plain numpy object array, not pyarrow-backed
X_text = df['text'].astype(str).to_numpy()

# Y should already be a numpy array from MultiLabelBinarizer, but ensure it explicitly
Y_arr = np.asarray(Y)

# use a fresh plain numpy range instead of df.index.values (which can also be pyarrow-backed after read_parquet)
row_indices = np.arange(len(df))

X_train_text, X_test_text, Y_train, Y_test, idx_train, idx_test = train_test_split(
    X_text,
    Y_arr,
    row_indices,
    test_size=0.15,
    random_state=42,
)

print(f"Train: {len(X_train_text):,} | Test: {len(X_test_text):,}")

Train: 254,997 | Test: 45,000

In [24]:
# # TF-IDF vectorization on the preprocessed text
# from sklearn.feature_extraction.text import TfidfVectorizer

# # note: stop_words='english' is now redundant since we already removed stopwords manually,
# # but leaving it doesn't hurt — it's a no-op safety net
# # force TfidfVectorizer to use our own NLTK tokenization instead of its default regex tokenizer
# from nltk.tokenize import word_tokenize

# tfidf = TfidfVectorizer(
#     max_features=30000,
#     ngram_range=(1, 2),
#     min_df=5,
#     max_df=0.8,
#     sublinear_tf=True,
#     tokenizer=word_tokenize,   # use NLTK's tokenizer explicitly
#     token_pattern=None,        # required when supplying a custom tokenizer
# )

# # fit on train only, transform both train and test (prevents test-set leakage into vocabulary)
# X_train_tfidf = tfidf.fit_transform(X_train_text)
# X_test_tfidf = tfidf.transform(X_test_text)

# # print resulting feature matrix shapes
# print("TF-IDF train shape:", X_train_tfidf.shape)
# print("TF-IDF test shape:", X_test_tfidf.shape)

In [ ]:
# TF-IDF vectorization using scikit-learn's default tokenizer (faster than custom NLTK tokenizer)
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=30000,     # cap vocabulary size
    ngram_range=(1, 2),     # unigrams + bigrams
    min_df=5,               # ignore very rare terms
    max_df=0.8,             # ignore overly common terms
    sublinear_tf=True,      # log-scale term frequency
    # no tokenizer/token_pattern override — uses sklearn's built-in fast regex tokenizer
    # this is fine since our text is already cleaned/lemmatized/space-separated
)

# fit on train only, transform both train and test
X_train_tfidf = tfidf.fit_transform(X_train_text)
X_test_tfidf = tfidf.transform(X_test_text)

print("TF-IDF train shape:", X_train_tfidf.shape)
print("TF-IDF test shape:", X_test_tfidf.shape)

TF-IDF train shape: (254997, 50000)
TF-IDF test shape: (45000, 50000)

# logistic regression classifier SGD optimizer

In [28]:
# retrain with class_weight='balanced' to counteract severe class imbalance across categories
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import SGDClassifier

clf = OneVsRestClassifier(
    SGDClassifier(
        loss='log_loss',
        max_iter=1000,
        random_state=42,
        class_weight='balanced',   # upweights rare classes during training
    ),
    n_jobs=1
)

clf.fit(X_train_tfidf, Y_train)

print("Training done.")

Training done.

In [29]:
# re-evaluate with the same metrics as before, to compare against the previous run
from sklearn.metrics import classification_report, f1_score, hamming_loss

Y_pred = clf.predict(X_test_tfidf)

print("Micro F1:", f1_score(Y_test, Y_pred, average='micro'))
print("Macro F1:", f1_score(Y_test, Y_pred, average='macro'))
print("Hamming Loss:", hamming_loss(Y_test, Y_pred))
print()
print(classification_report(Y_test, Y_pred, target_names=label_names))

Micro F1: 0.6590906428295278
Macro F1: 0.5341592995564718
Hamming Loss: 0.06466444444444444

              precision    recall  f1-score   support

    astro-ph       0.86      0.94      0.90      5540
    cond-mat       0.68      0.92      0.78      6002
          cs       0.86      0.93      0.90     14181
        econ       0.12      0.88      0.22       238
        eess       0.26      0.91      0.40      1903
       gr-qc       0.51      0.93      0.66      1745
      hep-ex       0.30      0.92      0.46       929
     hep-lat       0.22      0.91      0.36       455
      hep-ph       0.54      0.93      0.69      2888
      hep-th       0.47      0.91      0.62      2666
        math       0.79      0.90      0.84     11130
     math-ph       0.15      0.89      0.25      1281
        nlin       0.16      0.85      0.27       690
     nucl-ex       0.18      0.91      0.31       446
     nucl-th       0.30      0.92      0.46       940
     physics       0.40      0.84      0.55      4537
       q-bio       0.29      0.91      0.44       806
       q-fin       0.29      0.91      0.45       368
    quant-ph       0.54      0.91      0.67      2680
        stat       0.32      0.89      0.47      2208

   micro avg       0.52      0.91      0.66     61633
   macro avg       0.41      0.91      0.53     61633
weighted avg       0.64      0.91      0.73     61633
 samples avg       0.62      0.94      0.71     61633

c:\Users\hp\Desktop\ML project CDAC\cdac-aiml-project\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [30]:
# manually compute softer class weights (square root dampens the extreme imbalance correction)
import numpy as np

class_counts = Y_train.sum(axis=0)
n_samples = Y_train.shape[0]
n_classes = Y_train.shape[1]

# sqrt-dampened balanced weights instead of full inverse-frequency weighting
soft_weights = np.sqrt(n_samples / (n_classes * class_counts))

In [31]:
# get probability scores instead of hard 0/1 predictions
Y_proba = clf.predict_proba(X_test_tfidf)

# try a stricter threshold (e.g. 0.6-0.7) instead of default 0.5 for a stronger precision/recall balance
threshold = 0.5  # tune this
Y_pred_thresholded = (Y_proba >= threshold).astype(int)

In [32]:
# get prediction probabilities instead of hard 0/1 labels, so we can test different thresholds
Y_proba = clf.predict_proba(X_test_tfidf)
print("Probability matrix shape:", Y_proba.shape)

Probability matrix shape: (45000, 20)

In [34]:
# extend the threshold search higher, since scores were still improving at 0.7
from sklearn.metrics import f1_score

for threshold in [0.7, 0.75, 0.8, 0.85, 0.9, 0.95]:
    Y_pred_t = (Y_proba >= threshold).astype(int)
    macro_f1 = f1_score(Y_test, Y_pred_t, average='macro')
    micro_f1 = f1_score(Y_test, Y_pred_t, average='micro')
    print(f"Threshold={threshold} | Macro F1={macro_f1:.4f} | Micro F1={micro_f1:.4f}")

Threshold=0.7 | Macro F1=0.6183 | Micro F1=0.7337
Threshold=0.75 | Macro F1=0.6273 | Micro F1=0.7335
Threshold=0.8 | Macro F1=0.6238 | Micro F1=0.7172
Threshold=0.85 | Macro F1=0.6013 | Micro F1=0.6760
Threshold=0.9 | Macro F1=0.5409 | Micro F1=0.5887
Threshold=0.95 | Macro F1=0.3931 | Micro F1=0.3876

In [35]:
# use the best threshold found (0.75) for final evaluation
best_threshold = 0.75

Y_pred_final = (Y_proba >= best_threshold).astype(int)

from sklearn.metrics import classification_report, hamming_loss
print("Hamming Loss:", hamming_loss(Y_test, Y_pred_final))
print()
print(classification_report(Y_test, Y_pred_final, target_names=label_names))

Hamming Loss: 0.03628555555555556

              precision    recall  f1-score   support

    astro-ph       0.94      0.84      0.89      5540
    cond-mat       0.87      0.74      0.80      6002
          cs       0.94      0.77      0.85     14181
        econ       0.23      0.67      0.35       238
        eess       0.48      0.67      0.56      1903
       gr-qc       0.68      0.78      0.73      1745
      hep-ex       0.40      0.80      0.53       929
     hep-lat       0.45      0.79      0.57       455
      hep-ph       0.70      0.78      0.74      2888
      hep-th       0.68      0.75      0.71      2666
        math       0.93      0.73      0.82     11130
     math-ph       0.29      0.57      0.38      1281
        nlin       0.36      0.60      0.45       690
     nucl-ex       0.31      0.81      0.45       446
     nucl-th       0.47      0.78      0.59       940
     physics       0.67      0.47      0.55      4537
       q-bio       0.57      0.68      0.62       806
       q-fin       0.53      0.72      0.61       368
    quant-ph       0.72      0.75      0.74      2680
        stat       0.58      0.65      0.61      2208

   micro avg       0.74      0.73      0.73     61633
   macro avg       0.59      0.72      0.63     61633
weighted avg       0.79      0.73      0.75     61633
 samples avg       0.74      0.79      0.73     61633

c:\Users\hp\Desktop\ML project CDAC\cdac-aiml-project\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

# save preprocessing artifacts (TF-IDF vectorizer + label binarizer) as one pickle file

In [36]:
# save preprocessing artifacts (TF-IDF vectorizer + label binarizer) as one pickle file
import pickle
import os

SAVE_DIR = 'C:/Users/hp/Desktop/ML project CDAC/cdac-aiml-project/models'
os.makedirs(SAVE_DIR, exist_ok=True)

preprocessing_artifacts = {
    'tfidf_vectorizer': tfidf,
    'mlb_labels': mlb,
}

with open(f'{SAVE_DIR}/preprocessing.pkl', 'wb') as f:
    pickle.dump(preprocessing_artifacts, f)

print("Saved preprocessing.pkl")

Saved preprocessing.pkl

In [37]:
# save the trained model AND the chosen decision threshold together
# (threshold must travel with the model since .predict() alone uses a hardcoded 0.5, not our tuned 0.75)
model_artifacts = {
    'classifier': clf,
    'threshold': 0.75,
}

with open(f'{SAVE_DIR}/model.pkl', 'wb') as f:
    pickle.dump(model_artifacts, f)

print("Saved model.pkl")

Saved model.pkl

# LogisticRegression with saga solver — recommended for large sparse datasets like TF-IDF

In [ ]:
# LogisticRegression with saga solver — recommended for large sparse datasets like TF-IDF
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

clf_saga = OneVsRestClassifier(
    LogisticRegression(
        solver='saga',
        max_iter=1000,
        class_weight='balanced',
        random_state=42,
    ),
    n_jobs=1   # keep sequential to avoid the earlier Windows memmap issue
)

clf_saga.fit(X_train_tfidf, Y_train)
print("Training done.")

c:\Users\hp\Desktop\ML project CDAC\cdac-aiml-project\myenv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\hp\Desktop\ML project CDAC\cdac-aiml-project\myenv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\hp\Desktop\ML project CDAC\cdac-aiml-project\myenv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\hp\Desktop\ML project CDAC\cdac-aiml-project\myenv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\hp\Desktop\ML project CDAC\cdac-aiml-project\myenv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\hp\Desktop\ML project CDAC\cdac-aiml-project\myenv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\hp\Desktop\ML project CDAC\cdac-aiml-project\myenv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\hp\Desktop\ML project CDAC\cdac-aiml-project\myenv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\hp\Desktop\ML project CDAC\cdac-aiml-project\myenv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\hp\Desktop\ML project CDAC\cdac-aiml-project\myenv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

In [38]:
# train a multi-label classifier using Linear SVM (LinearSVC)
# LinearSVC is typically fast and works well on sparse high-dimensional data like TF-IDF
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import LinearSVC

svm_clf = OneVsRestClassifier(
    LinearSVC(
        class_weight='balanced',   # same imbalance fix that worked for logistic regression
        max_iter=2000,
        random_state=42,
    ),
    n_jobs=1   # sequential, avoids the earlier Windows joblib memmap crash
)

# fit on the same TF-IDF features used for the baseline model (fair comparison)
svm_clf.fit(X_train_tfidf, Y_train)

print("SVM training done.")

SVM training done.

In [39]:
# evaluate SVM on the same test set
from sklearn.metrics import classification_report, f1_score, hamming_loss

Y_pred_svm = svm_clf.predict(X_test_tfidf)

print("Micro F1:", f1_score(Y_test, Y_pred_svm, average='micro'))
print("Macro F1:", f1_score(Y_test, Y_pred_svm, average='macro'))
print("Hamming Loss:", hamming_loss(Y_test, Y_pred_svm))
print()
print(classification_report(Y_test, Y_pred_svm, target_names=label_names))

Micro F1: 0.7721534644460452
Macro F1: 0.6678304235973933
Hamming Loss: 0.03479444444444445

              precision    recall  f1-score   support

    astro-ph       0.89      0.94      0.92      5540
    cond-mat       0.78      0.90      0.84      6002
          cs       0.89      0.93      0.91     14181
        econ       0.45      0.55      0.50       238
        eess       0.44      0.74      0.55      1903
       gr-qc       0.66      0.84      0.74      1745
      hep-ex       0.49      0.76      0.60       929
     hep-lat       0.61      0.74      0.67       455
      hep-ph       0.69      0.88      0.77      2888
      hep-th       0.59      0.84      0.70      2666
        math       0.83      0.90      0.86     11130
     math-ph       0.26      0.61      0.36      1281
        nlin       0.38      0.58      0.46       690
     nucl-ex       0.48      0.69      0.56       446
     nucl-th       0.56      0.79      0.66       940
     physics       0.50      0.76      0.60      4537
       q-bio       0.57      0.72      0.64       806
       q-fin       0.65      0.71      0.68       368
    quant-ph       0.68      0.85      0.75      2680
        stat       0.49      0.75      0.59      2208

   micro avg       0.70      0.86      0.77     61633
   macro avg       0.60      0.77      0.67     61633
weighted avg       0.73      0.86      0.79     61633
 samples avg       0.78      0.91      0.81     61633

c:\Users\hp\Desktop\ML project CDAC\cdac-aiml-project\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [40]:
# save the SVM model as a separate pickle file (best model so far)
import pickle

with open(f'{SAVE_DIR}/model_svm.pkl', 'wb') as f:
    pickle.dump(svm_clf, f)

print("Saved model_svm.pkl")

Saved model_svm.pkl

In [43]:
# retrain Naive Bayes with class priors set inversely proportional to frequency,
# to counteract the same imbalance problem seen with the default (unbalanced) run
import numpy as np
from sklearn.multiclass import OneVsRestClassifier
from sklearn.naive_bayes import MultinomialNB

# NOTE: MultinomialNB inside OneVsRestClassifier treats each category as its own binary problem,
# so class_prior needs to be set per binary classifier — but OneVsRestClassifier doesn't let us
# pass different priors per underlying estimator directly through one shared instance.
# Instead, we manually loop over each label and fit a separate MultinomialNB with balanced priors.

n_classes = Y_train.shape[1]
nb_estimators = []

for i in range(n_classes):
    y_col = Y_train[:, i]
    pos_frac = y_col.mean()          # fraction of positive examples for this category
    neg_frac = 1 - pos_frac

    # invert the natural frequency so the rarer class gets a higher prior
    # (small pos_frac -> high weight given to positive class)
    prior_pos = neg_frac
    prior_neg = pos_frac
    # normalize so priors sum to 1
    total = prior_pos + prior_neg
    class_prior = [prior_neg / total, prior_pos / total]

    nb = MultinomialNB(class_prior=class_prior)
    nb.fit(X_train_tfidf, y_col)
    nb_estimators.append(nb)

print("Naive Bayes (balanced priors) training done.")

Naive Bayes (balanced priors) training done.

In [45]:
# manually predict using each per-category classifier and stack results into one matrix
import numpy as np

Y_pred_nb_balanced = np.column_stack([est.predict(X_test_tfidf) for est in nb_estimators])

from sklearn.metrics import classification_report, f1_score, hamming_loss

print("Micro F1:", f1_score(Y_test, Y_pred_nb_balanced, average='micro'))
print("Macro F1:", f1_score(Y_test, Y_pred_nb_balanced, average='macro'))
print("Hamming Loss:", hamming_loss(Y_test, Y_pred_nb_balanced))
print()
print(classification_report(Y_test, Y_pred_nb_balanced, target_names=label_names))

Micro F1: 0.2580765928880799
Macro F1: 0.25761480045526336
Hamming Loss: 0.3831366666666667

              precision    recall  f1-score   support

    astro-ph       0.55      0.98      0.71      5540
    cond-mat       0.45      0.98      0.62      6002
          cs       0.81      0.95      0.88     14181
        econ       0.01      0.98      0.02       238
        eess       0.09      1.00      0.17      1903
       gr-qc       0.08      1.00      0.14      1745
      hep-ex       0.07      0.99      0.12       929
     hep-lat       0.02      0.99      0.04       455
      hep-ph       0.21      0.99      0.34      2888
      hep-th       0.14      1.00      0.24      2666
        math       0.69      0.94      0.80     11130
     math-ph       0.06      0.99      0.11      1281
        nlin       0.02      0.99      0.05       690
     nucl-ex       0.02      1.00      0.05       446
     nucl-th       0.04      1.00      0.08       940
     physics       0.19      0.99      0.32      4537
       q-bio       0.03      1.00      0.05       806
       q-fin       0.02      0.99      0.03       368
    quant-ph       0.11      1.00      0.20      2680
        stat       0.10      1.00      0.18      2208

   micro avg       0.15      0.97      0.26     61633
   macro avg       0.19      0.99      0.26     61633
weighted avg       0.45      0.97      0.55     61633
 samples avg       0.18      0.98      0.29     61633

##naive bays is not performing well on this dataset

In [46]:
# build a comparison table of evaluation metrics: SGD (Logistic Regression, threshold=0.75) vs SVM
import pandas as pd
from sklearn.metrics import classification_report, f1_score, hamming_loss

# --- overall metrics comparison ---
comparison_data = {
    'Metric': ['Micro F1', 'Macro F1', 'Hamming Loss'],
    'SGD (LogReg, threshold=0.75)': [
        f1_score(Y_test, Y_pred_final, average='micro'),
        f1_score(Y_test, Y_pred_final, average='macro'),
        hamming_loss(Y_test, Y_pred_final),
    ],
    'SVM (LinearSVC, balanced)': [
        f1_score(Y_test, Y_pred_svm, average='micro'),
        f1_score(Y_test, Y_pred_svm, average='macro'),
        hamming_loss(Y_test, Y_pred_svm),
    ],
}

overall_comparison_df = pd.DataFrame(comparison_data)
print("=== OVERALL METRICS COMPARISON ===")
print(overall_comparison_df.to_string(index=False))
print()

# --- per-category F1 comparison ---
sgd_report = classification_report(Y_test, Y_pred_final, target_names=label_names, output_dict=True, zero_division=0)
svm_report = classification_report(Y_test, Y_pred_svm, target_names=label_names, output_dict=True, zero_division=0)

per_category_comparison = pd.DataFrame({
    'Category': label_names,
    'SGD_F1': [sgd_report[cat]['f1-score'] for cat in label_names],
    'SVM_F1': [svm_report[cat]['f1-score'] for cat in label_names],
})

# add a column showing which model won for each category
per_category_comparison['Better_Model'] = per_category_comparison.apply(
    lambda row: 'SVM' if row['SVM_F1'] > row['SGD_F1'] else ('SGD' if row['SGD_F1'] > row['SVM_F1'] else 'Tie'),
    axis=1
)

# sort by SVM F1 descending for easier reading
per_category_comparison = per_category_comparison.sort_values('SVM_F1', ascending=False).reset_index(drop=True)

print("=== PER-CATEGORY F1 COMPARISON ===")
print(per_category_comparison.to_string(index=False))

# quick summary: how many categories each model won
print()
print("Categories won by each model:")
print(per_category_comparison['Better_Model'].value_counts())

=== OVERALL METRICS COMPARISON ===
      Metric  SGD (LogReg, threshold=0.75)  SVM (LinearSVC, balanced)
    Micro F1                      0.733488                   0.772153
    Macro F1                      0.627343                   0.667830
Hamming Loss                      0.036286                   0.034794

=== PER-CATEGORY F1 COMPARISON ===
Category   SGD_F1   SVM_F1 Better_Model
astro-ph 0.887572 0.915927          SVM
      cs 0.847616 0.909611          SVM
    math 0.818551 0.861919          SVM
cond-mat 0.797722 0.836307          SVM
  hep-ph 0.741713 0.770919          SVM
quant-ph 0.735030 0.753902          SVM
   gr-qc 0.725631 0.741132          SVM
  hep-th 0.714721 0.695490          SGD
   q-fin 0.614319 0.677083          SVM
 hep-lat 0.574841 0.670000          SVM
 nucl-th 0.590124 0.656071          SVM
   q-bio 0.619876 0.641054          SVM
 physics 0.549642 0.602997          SVM
  hep-ex 0.530249 0.597370          SVM
    stat 0.613752 0.591661          SGD
 nucl-ex 0.450125 0.563536          SVM
    eess 0.557046 0.551901          SGD
    econ 0.346783 0.495238          SVM
    nlin 0.448891 0.460473          SVM
 math-ph 0.382645 0.364018          SGD

Categories won by each model:
Better_Model
SVM    16
SGD     4
Name: count, dtype: int64

In [1]:
# make sure preprocess_text is defined/imported in this session (same function used during training)
# test cases: 4 sample title+abstract pairs from different subject areas
test_cases = [
    {
        "title": "Deep Learning Approaches for Galaxy Classification in Astronomical Surveys",
        "abstract": "We propose a convolutional neural network architecture for classifying galaxy morphology from large-scale astronomical survey images, achieving state-of-the-art accuracy on benchmark datasets.",
    },
    {
        "title": "A New Algorithm for Solving Sparse Linear Systems",
        "abstract": "We present a novel iterative method for solving large sparse linear systems arising in numerical optimization, with convergence guarantees under mild assumptions.",
    },
    {
        "title": "Quantum Entanglement in Many-Body Systems",
        "abstract": "We study the entanglement entropy of ground states in strongly correlated many-body quantum systems using tensor network methods.",
    },
    {
        "title": "Macroeconomic Effects of Interest Rate Policy",
        "abstract": "This paper examines the transmission mechanism of monetary policy on inflation and unemployment using a dynamic stochastic general equilibrium model.",
    },
]

# run preprocessing + TF-IDF transform on each test case, check output shape
for i, case in enumerate(test_cases):
    raw_text = case["title"] + " " + case["abstract"]
    cleaned_text = preprocess_text(raw_text)              # apply same manual cleaning as training
    text_tfidf = tfidf.transform([cleaned_text])           # transform using FITTED vectorizer

    print(f"--- Test case {i+1} ---")
    print("Cleaned text (first 100 chars):", cleaned_text[:100])
    print("TF-IDF vector shape:", text_tfidf.shape)          # should be (1, 30000)
    print("Non-zero features:", text_tfidf.nnz)               # how many words actually matched the vocabulary
    print()

NameError: name 'preprocess_text' is not defined

In [ ]:
# full pipeline: preprocess -> tfidf transform -> predict -> decode category names
for i, case in enumerate(test_cases):
    raw_text = case["title"] + " " + case["abstract"]
    cleaned_text = preprocess_text(raw_text)
    text_tfidf = tfidf.transform([cleaned_text])

    prediction = svm_clf.predict(text_tfidf)
    predicted_categories = mlb.inverse_transform(prediction)[0]

    print(f"--- Test case {i+1} ---")
    print("Title:", case["title"])
    print("Predicted categories:", predicted_categories)
    print()